version: "3.7"

services:
  sl-postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - sl-network
    volumes:
      - ./sldb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=somethingspecialhere
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simplelogin

  sl-init:
    image: simplelogin/app:3.4.0
    restart: unless-stopped
    depends_on:
      - sl-postgres
    command: python init_app.py
    networks:
      - sl-network
    volumes:
      - ./sl:/sl
      - ./slupload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key

  sl-app:
    image: simplelogin/app:3.4.0
    restart: unless-stopped
    depends_on:
      - sl-postgres
      - sl-email
    ports:
      - "7777:7777"
    networks:
      - sl-network
    volumes:
      - ./sl:/sl
      - ./slupload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key

  sl-email:
    image: simplelogin/app:3.4.0
    restart: unless-stopped
    depends_on:
      - sl-postgres
    command: python email_handler.py
    ports:
      - "20381:20381"
    networks:
      - sl-network
    volumes:
      - ./sl:/sl
      - ./slupload:/code/static/upload
      - ./simplelogin.env:/code/.env
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
volumes:
  sl:
  sldb:
  slupload:
networks:
  sl-network:
    driver: bridge